"""
SANDHI — synthetic cohort + signal simulator.

This is Build-Order step (1) from the architecture: "Signal spec + synthetic data gen".
It exists so the app and the model can be built before the physical kit is finished.

IMPORTANT / HONESTY NOTE
------------------------
Every subject produced here is SYNTHETIC. The generative parameters below are
seeded from published ranges for knee-OA gait and vibroarthrography (see
docs/REFERENCES.md) but no real patient data is used anywhere in this repo.
Any accuracy number computed on this cohort measures how learnable THIS
SIMULATOR is. It is not clinical validation. Say that out loud.

Sampling rate (frozen — firmware and app must match):
    IMU   100 Hz   (thigh + shank, 3-axis accel + 3-axis gyro)
"""
import numpy as np

FS_IMU = 100
WALK_SECONDS = 30
STS_REPS = 5

# ---------------------------------------------------------------- subject ---

# Residual biological variance not explained by any question the ASHA asks.
# Set high on purpose: a questionnaire cannot see inside a knee.
BIO_NOISE = 1.95

OCCUPATIONS = [
    # name,                squat_load 0-3, stairs/day, terrain slope index 0-1
    ("Terrace farming",          3, 180, 0.86),
    ("Tea garden work",          3, 120, 0.61),
    ("Livestock / grazing",      2, 200, 0.90),
    ("Head-load portering",      3, 240, 0.93),
    ("Weaving (floor loom)",     3,  30, 0.20),
    ("Homemaker",                2,  60, 0.35),
    ("Shopkeeper",               1,  40, 0.28),
    ("School teacher",           0,  70, 0.32),
    ("Driver",                   1,  25, 0.30),
    ("Construction labour",      2, 150, 0.55),
    ("Office / clerical",        0,  35, 0.25),
    ("Student",                  0, 110, 0.40),
]


def sample_subject(rng):
    """Draw one synthetic villager with a causal latent OA severity."""
    age = float(np.clip(rng.normal(46, 15), 18, 88))
    sex_f = int(rng.random() < 0.54)          # ASHA screening skews female
    bmi = float(np.clip(rng.normal(24.4 + 0.02 * (age - 40), 3.6), 15.5, 41))
    occ_i = rng.integers(0, len(OCCUPATIONS))
    occ_name, squat, stairs, terrain = OCCUPATIONS[occ_i]
    stairs = float(max(0, rng.normal(stairs, stairs * 0.25)))
    terrain = float(np.clip(rng.normal(terrain, 0.08), 0, 1))
    prior_injury = int(rng.random() < 0.11)
    family_hx = int(rng.random() < 0.18)

    # ---- latent structural severity (drives BOTH signals and label) --------
    # Coefficients are shaped to reproduce the direction + rough effect size of
    # established risk factors; they are not fitted to any real cohort.
    lin = (
        -3.90
        + 0.062 * (age - 40)
        + 0.088 * (bmi - 23)
        + 0.42 * sex_f
        + 0.30 * squat
        + 0.0022 * stairs
        + 0.95 * terrain
        + 0.85 * prior_injury
        + 0.55 * family_hx
        + 0.019 * (age - 40) * max(0.0, bmi - 25) * 0.10
    )
    lin += rng.normal(0, BIO_NOISE)            # unexplained biology
    sev = 1.0 / (1.0 + np.exp(-lin))          # 0..1 latent structural damage

    # Radiographic proxy. KL>=2 == "definite OA" == our positive class.
    kl_cuts = [0.18, 0.40, 0.62, 0.83]
    kl = int(np.searchsorted(kl_cuts, sev))

    # ---- reader disagreement -----------------------------------------
    # KL grading is only moderately reliable between radiologists (kappa in the
    # 0.5-0.7 range). Our "ground truth" therefore carries real label noise, and
    # pretending otherwise would inflate every metric downstream.
    if rng.random() < 0.10:
        kl = int(np.clip(kl + (1 if rng.random() < 0.5 else -1), 0, 4))

    # ---- structure -> function is a WEAK link -------------------------
    # The structure/symptom discordance in knee OA is one of the most
    # replicated findings in the literature: plenty of KL-3 knees walk fine and
    # plenty of KL-0 knees hurt. Gait deficits therefore get their own latent,
    # only partly explained by structural damage.
    age_decl = float(np.clip((age - 55.0) / 35.0, 0, 1))     # sarcopenia, balance
    bmi_mech = float(np.clip((bmi - 27.0) / 12.0, 0, 1))     # mass, not cartilage
    # Non-OA causes of an impaired gait: low back pain, old ankle fracture,
    # hip pathology, neuropathy. These are the false positives we must expect.
    other_cause = float(rng.random() < 0.12) * float(rng.random())
    sev_func = float(np.clip(
        0.66 * sev + 0.18 * age_decl + 0.12 * bmi_mech + 0.30 * other_cause
        + rng.normal(0, 0.17), 0, 1))

    # Crepitus is generated by the joint surface itself, so it tracks structure
    # more tightly than gait does -- but only if the piezo is coupled well.
    sev_vag = float(np.clip(0.78 * sev + 0.10 * age_decl + rng.normal(0, 0.15), 0, 1))
    coupling = float(np.clip(rng.normal(1.0, 0.30), 0.30, 1.9))

    # Symptoms sit between structure and function, loosely.
    sym = 0.45 * sev + 0.40 * sev_func + 0.15 * other_cause
    womac_pain = float(np.clip(rng.normal(2.2 + 13.5 * sym, 3.6), 0, 20))
    womac_stiff = float(np.clip(rng.normal(0.7 + 5.4 * sym, 1.7), 0, 8))

    return dict(
        age=age, sex_f=sex_f, bmi=bmi,
        occupation=occ_name, occ_squat_load=float(squat),
        stairs_per_day=stairs, terrain_slope_idx=terrain,
        prior_injury=prior_injury, family_hx=family_hx,
        womac_pain=womac_pain, womac_stiff=womac_stiff,
        _sev=float(sev), _sev_func=sev_func, _sev_vag=sev_vag,
        _coupling=coupling, _other_cause=other_cause,
        kl_grade=kl, label=int(kl >= 2),
    )


# ------------------------------------------------------------- gait signal ---

def synth_walk(rng, sev, nuisance=None):
    """30 s of level walking. Returns dict of channels at 100 Hz.

    Severity effects encoded (all documented in docs/REFERENCES.md):
      - cadence falls, stride time rises
      - knee flexion excursion in swing is reduced ("stiff-knee gait")
      - stance % and double-support % rise (offloading / cautious gait)
      - stride-to-stride variability rises
      - left/right asymmetry rises (usually unilateral disease)
    """
    nz = nuisance or {}
    # Real-world nuisance: strap tension and cuff rotation change the effective
    # gyro gain; footwear and ground surface change impact magnitude; the ASHA
    # worker does not measure a 30 s walk with a stopwatch.
    gyro_gain = nz.get("gyro_gain", 1.0)
    accel_gain = nz.get("accel_gain", 1.0)
    noise_gain = nz.get("noise_gain", 1.0)

    n = WALK_SECONDS * FS_IMU
    t = np.arange(n) / FS_IMU

    stride_T = 1.06 + 0.30 * sev + rng.normal(0, 0.035)      # seconds
    cv = 0.021 + 0.055 * sev                                  # stride-time CV
    rom = 62.0 - 19.0 * sev + rng.normal(0, 2.6)              # knee flex ROM deg
    stance_frac = 0.605 + 0.055 * sev
    asym = 0.012 + 0.085 * sev * rng.random()

    # Build a stride-by-stride phase clock with realistic variability.
    phases, cursor, k = [], 0.0, 0
    while cursor < WALK_SECONDS + 2 * stride_T:
        jitter = rng.normal(0, cv * stride_T)
        side = 1.0 + (asym if k % 2 else -asym)
        dur = max(0.55, stride_T * side + jitter)
        phases.append((cursor, dur))
        cursor += dur
        k += 1

    knee = np.zeros(n)
    shank_gyro = np.zeros(n)
    thigh_gyro = np.zeros(n)
    shank_acc = np.zeros(n)

    for (t0, dur) in phases:
        i0 = int(t0 * FS_IMU)
        i1 = min(n, int((t0 + dur) * FS_IMU))
        if i0 >= n or i1 <= i0:
            continue
        p = (np.arange(i1 - i0) / (i1 - i0))            # 0..1 within stride

        # Knee flexion: small loading-response bump in stance, big swing peak.
        stance_bump = 16.0 * np.exp(-((p - 0.13) ** 2) / (2 * 0.055 ** 2))
        swing_peak_c = stance_frac + (1 - stance_frac) * 0.42
        swing = rom * np.exp(-((p - swing_peak_c) ** 2) / (2 * 0.075 ** 2))
        knee[i0:i1] += 4.0 + stance_bump * (1 - 0.35 * sev) + swing

        # Shank angular velocity: sharp mid-swing peak, reduced with severity.
        pk = (430.0 - 150.0 * sev)
        sw_sigma = 0.092 - 0.019 * sev          # stiff-knee gait = shorter swing lobe
        shank_gyro[i0:i1] += pk * np.exp(-((p - swing_peak_c) ** 2) / (2 * sw_sigma ** 2))
        shank_gyro[i0:i1] -= (150.0 - 45.0 * sev) * np.exp(-((p - 0.06) ** 2) / (2 * 0.045 ** 2))
        thigh_gyro[i0:i1] += (210.0 - 62.0 * sev) * np.exp(-((p - swing_peak_c + 0.06) ** 2) / (2 * 0.085 ** 2))

        # Heel strike + toe off impact transients on the shank accelerometer.
        hs = i0
        to = i0 + int((i1 - i0) * stance_frac)
        impact = (2.35 - 0.72 * sev)                    # g, damped by guarding
        for idx, amp in ((hs, impact), (to, impact * 0.45)):
            if 0 <= idx < n - 12:
                dpk = amp * np.exp(-np.arange(12) / 2.4) * np.cos(np.arange(12) * 1.15)
                shank_acc[idx:idx + 12] += dpk

    shank_gyro *= gyro_gain
    thigh_gyro *= gyro_gain
    shank_acc *= accel_gain
    shank_acc += 1.0 + 0.22 * np.sin(2 * np.pi * t / stride_T)
    knee += rng.normal(0, 0.9 * noise_gain, n)
    shank_gyro += rng.normal(0, 7.5 * noise_gain, n)
    thigh_gyro += rng.normal(0, 6.0 * noise_gain, n)
    shank_acc += rng.normal(0, 0.045 * noise_gain, n)

    return dict(knee_angle=knee, shank_gyro=shank_gyro,
                thigh_gyro=thigh_gyro, shank_acc=shank_acc, fs=FS_IMU)


# --------------------------------------------------------- sit-to-stand -----

def synth_sts(rng, sev, nuisance=None):
    """5 sit-to-stand repetitions. Slower, less smooth, more asymmetric with OA."""
    gyro_gain = (nuisance or {}).get("gyro_gain", 1.0)
    rep_T = 1.72 + 1.55 * sev + rng.normal(0, 0.18)   # seconds per rep
    rest = 0.42 + 0.30 * sev
    total = STS_REPS * (rep_T + rest) + 1.2
    n = int(total * FS_IMU)
    thigh = np.zeros(n)
    trunk = np.zeros(n)
    cursor = 0.6
    for r in range(STS_REPS):
        dur = max(0.8, rep_T * (1 + rng.normal(0, 0.06 + 0.09 * sev)))
        i0, i1 = int(cursor * FS_IMU), min(n, int((cursor + dur) * FS_IMU))
        if i1 <= i0:
            break
        p = np.arange(i1 - i0) / (i1 - i0)
        peak = 205.0 - 96.0 * sev
        rise = peak * np.exp(-((p - 0.32) ** 2) / (2 * 0.13 ** 2))
        fall = -peak * 0.82 * np.exp(-((p - 0.74) ** 2) / (2 * 0.15 ** 2))
        # Severity adds a hesitation notch (momentum-transfer strategy loss).
        notch = 1.0 - 0.30 * sev * np.exp(-((p - 0.47) ** 2) / (2 * 0.05 ** 2))
        thigh[i0:i1] += (rise + fall) * notch
        trunk[i0:i1] += (128.0 + 52.0 * sev) * np.exp(-((p - 0.22) ** 2) / (2 * 0.11 ** 2))
        cursor += dur + max(0.15, rest * (1 + rng.normal(0, 0.2)))
    thigh = thigh * gyro_gain + rng.normal(0, 5.5, n)
    trunk = trunk * gyro_gain + rng.normal(0, 4.5, n)
    return dict(thigh_gyro=thigh, trunk_gyro=trunk, fs=FS_IMU)


# --------------------------------------------------- vibroarthrography ------

def synth_session(rng, subj):
    """One full 3-minute screening: walk + five sit-to-stands."""
    nuisance = dict(
        gyro_gain=float(np.clip(rng.normal(1.0, 0.055), 0.80, 1.20)),
        accel_gain=float(np.clip(rng.normal(1.0, 0.09), 0.70, 1.35)),
        noise_gain=float(np.clip(rng.normal(1.0, 0.22), 0.55, 2.10)),
    )
    return dict(
        walk=synth_walk(rng, subj["_sev_func"], nuisance),
        sts=synth_sts(rng, subj["_sev_func"], nuisance),
        nuisance=nuisance,
    )
