"use client";
import * as React from "react";
import { TopBar } from "@/components/Shell";
import { Card, CardHead, Chip, SimBadge, Section, PageHead, Stat, Skeleton, Bar } from "@/components/ui";
import { RocCurve, CalibrationPlot, HBars, Histogram } from "@/components/Charts";
import { IcAlert, IcFlask, IcCheck, IcSpark, IcModel } from "@/components/Icons";
import { useSandhi, pct, int, num, FEATURE_LABEL, FEATURE_UNIT, CHANNEL_CHIP, CHANNEL_LABEL } from "@/lib/store";
import { FEATURE_CHANNEL } from "@/lib/dsp/features";

export default function ModelCard() {
  const { metrics, model, cohort } = useSandhi();
  const [thr, setThr] = React.useState<number | null>(null);

  const op = React.useMemo(() => {
    if (!metrics) return null;
    const t = thr ?? metrics.bands.refer;
    // Nearest measured operating point from the held-out sweep. We never
    // interpolate a sensitivity we did not actually observe.
    return metrics.threshold_sweep.reduce((best, p) =>
      Math.abs(p.threshold - t) < Math.abs(best.threshold - t) ? p : best);
  }, [metrics, thr]);

  if (!metrics || !model || !op) {
    return (<><TopBar title="Model card" /><div className="page"><Skeleton h={300} /></div></>);
  }

  const total = op.tp + op.fp + op.fn + op.tn;
  const per1000 = ((op.tp + op.fp) / total) * 1000;
  const missedPer1000 = (op.fn / total) * 1000;
  const klDist = metrics.cohort.kl_distribution;
  const klTotal = Object.values(klDist).reduce((a, b) => a + b, 0);

  const riskDist = cohort ? cohort.records.map((r) => r.risk) : [];

  return (
    <>
      <TopBar title="Model card" right={<Chip tone="chip-lilac">v0.4 · {metrics.model.trees} trees</Chip>} />
      <div className="page">
        <PageHead
          eyebrow="Layer 4 — model"
          title="Model card"
          lead="What the model is, what it was trained on, how well it does and where it will fail. Written so the numbers here cannot be quoted out of context."
        />

        {/* -------------------------------------------- the honest banner - */}
        <div className="card" style={{
          background: "var(--amber-bg)", borderColor: "var(--amber-line)", padding: "16px 18px",
        }}>
          <div className="row" style={{ gap: 12, alignItems: "flex-start" }}>
            <span style={{ color: "var(--amber-ink)", marginTop: 1 }}><IcAlert size={17} /></span>
            <div>
              <div style={{ fontWeight: 640, fontSize: 14, color: "var(--amber-ink)" }}>
                Every number on this page was measured on synthetic data.
              </div>
              <p style={{ marginTop: 6, fontSize: 13, lineHeight: 1.6, color: "var(--amber-ink)", opacity: .92, maxWidth: 800 }}>
                The cohort is {int(metrics.cohort.total)} subjects generated by <span className="mono">ml/simulator.py</span>,
                whose generative parameters follow published ranges for knee-OA gait and vibroarthrography.
                These metrics quantify <em>how learnable the simulator is</em>. They are not clinical
                validation, they are not accuracy on patients, and they must never be presented as either.
                What they do establish is that the pipeline — capture, features, training, calibration,
                on-device inference — is complete and correct end to end. Point it at real captures and
                every number on this page is replaced.
              </p>
            </div>
          </div>
        </div>

        {/* ---------------------------------------------------- headline - */}
        <div className="grid g4" style={{ marginTop: 16 }}>
          <Stat label="Held-out AUC" value={metrics.test.auc.toFixed(3)}
                sub={<>{int(metrics.cohort.test)} unseen subjects</>} />
          <Stat label="Brier score" value={metrics.test.brier.toFixed(3)}
                sub="lower is better — measures calibration, not just ranking" />
          <Stat label="Sensitivity at referral cut" value={pct(metrics.operating_points.refer.sensitivity, 1)}
                sub="chosen deliberately high: a missed case costs more than an extra PHC visit" />
          <Stat label="NPV at the low cut" value={pct(metrics.operating_points.low.npv, 1)}
                sub="a green result has to be genuinely reassuring" />
        </div>

        {/* ------------------------------------------------ curves ------- */}
        <Section title="Discrimination and calibration"
                 sub="Ranking ability and honesty of the probability are different properties. A screening tool needs both: the first to sort, the second so a 40% actually means 40%.">
          <div className="grid g3">
            <Card>
              <CardHead title="ROC" sub={`AUC ${metrics.test.auc.toFixed(3)}`} />
              <div className="card-bd" style={{ display: "grid", placeItems: "center" }}>
                <RocCurve points={metrics.roc}
                          marker={{ spec: op.specificity, sens: op.sensitivity }} />
                <div className="tiny dim" style={{ marginTop: 8, textAlign: "center" }}>
                  Marker is the current operating point below.
                </div>
              </div>
            </Card>
            <Card>
              <CardHead title="Calibration" sub="predicted vs observed, decile bins" />
              <div className="card-bd" style={{ display: "grid", placeItems: "center" }}>
                <CalibrationPlot bins={metrics.calibration} />
                <div className="tiny dim" style={{ marginTop: 8, textAlign: "center" }}>
                  Circle area is bin population. Close to the diagonal means the
                  number can be spoken aloud as a probability.
                </div>
              </div>
            </Card>
            <Card>
              <CardHead title="Score distribution" sub="where the registry actually lands" />
              <div className="card-bd">
                <Histogram values={riskDist} bins={28} height={132} color="var(--sky-line)"
                           cuts={[
                             { at: model.bands.low, color: "var(--sage-ink)" },
                             { at: model.bands.refer, color: "var(--clay-ink)" },
                           ]} />
                <div className="between tiny dim" style={{ marginTop: 6 }}>
                  <span>0</span>
                  <span className="num">cuts at {pct(model.bands.low, 0)} and {pct(model.bands.refer, 0)}</span>
                  <span>100%</span>
                </div>
                <div className="tiny dim" style={{ marginTop: 10, lineHeight: 1.55 }}>
                  The mass at the low end is the point of a screening tool: most
                  people should be sorted out quickly and cheaply.
                </div>
              </div>
            </Card>
          </div>
        </Section>

        {/* ---------------------------------------- threshold explorer --- */}
        <Section
          title="Choosing the referral threshold"
          sub="This is a policy decision, not a modelling one. Move the cut and watch what it costs the district in PHC visits and what it costs a patient in missed disease."
        >
          <Card>
            <div className="card-bd">
              <div className="row" style={{ gap: 20, alignItems: "center", flexWrap: "wrap" }}>
                <div className="grow" style={{ minWidth: 280 }}>
                  <div className="between" style={{ marginBottom: 8 }}>
                    <span className="label">Referral threshold</span>
                    <span className="row" style={{ gap: 10 }}>
                      <span className="serif num" style={{ fontSize: 20 }}>{pct(op.threshold, 0)}</span>
                      {thr !== null && (
                        <button className="btn btn-sm btn-ghost" onClick={() => setThr(null)}>
                          reset to shipped
                        </button>
                      )}
                    </span>
                  </div>
                  <input type="range" min={0.05} max={0.9} step={0.05}
                         value={thr ?? metrics.bands.refer}
                         onChange={(e) => setThr(+e.target.value)} />
                  <div className="between tiny dim" style={{ marginTop: 2 }}>
                    <span>catch everything</span>
                    <span>refer only the certain</span>
                  </div>
                </div>

                <div style={{ display: "grid", gridTemplateColumns: "repeat(4, minmax(84px, 1fr))", gap: 12 }}>
                  {[
                    ["Sensitivity", op.sensitivity, "cases caught"],
                    ["Specificity", op.specificity, "healthy correctly cleared"],
                    ["PPV", op.ppv, "of those referred, truly positive"],
                    ["NPV", op.npv, "of those cleared, truly negative"],
                  ].map(([l, v, s]) => (
                    <div key={l as string}>
                      <div className="eyebrow" style={{ fontSize: 9.6 }}>{l as string}</div>
                      <div className="serif num" style={{ fontSize: 21, marginTop: 3, lineHeight: 1 }}>
                        {pct(v as number, 0)}
                      </div>
                      <div className="tiny faint" style={{ marginTop: 3, lineHeight: 1.35 }}>{s as string}</div>
                    </div>
                  ))}
                </div>
              </div>

              <div className="grid g3" style={{ marginTop: 20, gap: 14 }}>
                <ConsequenceCard
                  tone="var(--sky-bg)" line="var(--sky-line)" ink="var(--sky-ink)"
                  head={`${Math.round(per1000)} per 1,000`}
                  label="Referrals generated"
                  body={`A district screening 10,000 adults sends about ${int(Math.round(per1000 * 10))} people to a PHC. Across the eight states' ${int(cohort?.districts.reduce((s, d) => s + d.phc, 0) ?? 0)} PHCs in this catchment that is roughly ${Math.round((per1000 * 10) / Math.max(1, cohort?.districts.reduce((s, d) => s + d.phc, 0) ?? 1))} extra knee consultations each.`}
                />
                <ConsequenceCard
                  tone="var(--clay-bg)" line="var(--clay-line)" ink="var(--clay-ink)"
                  head={`${missedPer1000.toFixed(1)} per 1,000`}
                  label="Cases missed"
                  body={`People with KL ≥ 2 whom this threshold sends home. At the shipped cut that is ${((metrics.operating_points.refer.fn / (metrics.operating_points.refer.fn + metrics.operating_points.refer.tp)) * 100).toFixed(0)}% of true cases — the price paid for not flooding the PHC.`}
                />
                <ConsequenceCard
                  tone="var(--sage-bg)" line="var(--sage-line)" ink="var(--sage-ink)"
                  head={`${pct(op.specificity, 0)}`}
                  label="Correctly sent home"
                  body="Every person correctly cleared is a day of wages not lost and a journey over bad road not taken. Specificity is not an abstraction here."
                />
              </div>

              <div style={{
                marginTop: 16, padding: "12px 14px", borderRadius: "var(--r-sm)",
                background: "var(--surface-2)", border: "1px solid var(--line)",
              }}>
                <div className="eyebrow" style={{ marginBottom: 5 }}>How the shipped cut was chosen</div>
                <div className="small muted" style={{ lineHeight: 1.6 }}>
                  The referral cut is the highest threshold that still holds sensitivity at or above
                  0.90 on the validation split — screening errs toward catching cases. The low cut is
                  the highest threshold that keeps NPV at or above 0.97, so a green result is worth
                  trusting. Both were fixed on validation data and only then measured on the test
                  split, which is the only order that makes the test numbers mean anything.
                </div>
              </div>
            </div>
          </Card>
        </Section>

        {/* ----------------------------------------- confusion + ablation - */}
        <div className="grid g2" style={{ marginTop: 30, gap: 14 }}>
          <Card>
            <CardHead title="Confusion matrix" sub={`at threshold ${pct(op.threshold, 0)}, on ${int(total)} held-out subjects`} />
            <div className="card-bd">
              <div style={{ display: "grid", gridTemplateColumns: "84px 1fr 1fr", gap: 7, alignItems: "stretch" }}>
                <div />
                <CMHead>Predicted refer</CMHead>
                <CMHead>Predicted clear</CMHead>
                <CMSide>Actually KL ≥ 2</CMSide>
                <CMCell n={op.tp} total={total} label="true positive" tone="var(--sage-bg)" line="var(--sage-line)" ink="var(--sage-ink)" />
                <CMCell n={op.fn} total={total} label="missed case" tone="var(--clay-bg)" line="var(--clay-line)" ink="var(--clay-ink)" />
                <CMSide>Actually KL &lt; 2</CMSide>
                <CMCell n={op.fp} total={total} label="unnecessary trip" tone="var(--amber-bg)" line="var(--amber-line)" ink="var(--amber-ink)" />
                <CMCell n={op.tn} total={total} label="true negative" tone="var(--sage-bg)" line="var(--sage-line)" ink="var(--sage-ink)" />
              </div>
              <div className="tiny dim" style={{ marginTop: 13, lineHeight: 1.55 }}>
                The two error cells are not equivalent. A missed case loses years of a knee; an
                unnecessary trip loses a day. The threshold is set accordingly.
              </div>
            </div>
          </Card>

          <Card>
            <CardHead title="What each sensor adds" sub="each row retrained from scratch and re-scored on the same split"
                      icon={<IcFlask size={14} />} />
            <div className="card-bd">
              <table className="tbl" style={{ fontSize: 12.6 }}>
                <thead><tr><th>Feature set</th><th className="rt">Inputs</th><th className="rt">AUC</th><th className="rt">Δ</th></tr></thead>
                <tbody>
                  {Object.entries(metrics.ablation).map(([k, v], i, arr) => {
                    const base = arr[0][1].auc;
                    return (
                      <tr key={k}>
                        <td style={{ fontWeight: i === arr.length - 1 ? 600 : 500 }}>{k}</td>
                        <td className="rt dim">{v.n_features}</td>
                        <td className="rt num" style={{ fontWeight: 570 }}>{v.auc.toFixed(3)}</td>
                        <td className="rt num" style={{ color: i === 0 ? "var(--ink-4)" : "var(--sage-ink)" }}>
                          {i === 0 ? "—" : `+${((v.auc - base) * 100).toFixed(1)}`}
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
              <div className="tiny dim" style={{ marginTop: 12, lineHeight: 1.55 }}>
                This is the table that justifies building hardware at all. Note the honest caveat:
                the acoustic channel dominates partly <em>because the simulator was written that way</em> —
                crepitus is modelled as a more direct read of the joint surface than gait, which is a
                defensible assumption but still an assumption. Real captures will move this table,
                and that is exactly what the first pilot is for.
              </div>
            </div>
          </Card>
        </div>

        {/* --------------------------------------------- importances ----- */}
        <Section title="What the model leans on" sub="Total loss reduction attributable to each input across all trees.">
          <Card>
            <div className="card-bd">
              <HBars
                fmt={(v) => `${(v * 100).toFixed(1)}%`}
                items={metrics.importances.slice(0, 14).map((r) => ({
                  label: FEATURE_LABEL[r.feature] ?? r.feature,
                  value: r.gain,
                  color: {
                    gait: "var(--sky-line)", sts: "var(--lilac-line)",
                    acoustic: "var(--blush-line)", intake: "var(--sage-line)",
                  }[FEATURE_CHANNEL[r.feature] ?? "intake"],
                }))}
              />
              <div className="row wrap" style={{ gap: 14, marginTop: 15, paddingTop: 12, borderTop: "1px solid var(--line-soft)" }}>
                {(["gait", "sts", "acoustic", "intake"] as const).map((c) => (
                  <span key={c} className={`chip ${CHANNEL_CHIP[c]}`}>{CHANNEL_LABEL[c]}</span>
                ))}
              </div>
            </div>
          </Card>
        </Section>

        {/* ------------------------------------------ cohort + training -- */}
        <div className="grid g3" style={{ marginTop: 30, gap: 14 }}>
          <Card>
            <CardHead title="Training cohort" sub="synthetic, generated once and frozen" />
            <div className="card-bd">
              <div className="kv"><dt>Subjects</dt><dd>{int(metrics.cohort.total)}</dd></div>
              <div className="kv"><dt>Train / val / test</dt><dd>{int(metrics.cohort.train)} · {int(metrics.cohort.val)} · {int(metrics.cohort.test)}</dd></div>
              <div className="kv"><dt>Prevalence (KL ≥ 2)</dt><dd>{pct(metrics.cohort.prevalence, 1)}</dd></div>
              <div style={{ marginTop: 12 }}>
                <div className="eyebrow" style={{ marginBottom: 7 }}>Kellgren–Lawrence grades</div>
                <div className="row" style={{ gap: 3, height: 34, alignItems: "flex-end" }}>
                  {[0, 1, 2, 3, 4].map((k) => {
                    const n = klDist[String(k)] ?? 0;
                    return (
                      <div key={k} className="grow" style={{ textAlign: "center" }}>
                        <div style={{
                          height: Math.max(3, (n / klTotal) * 90), borderRadius: "3px 3px 0 0",
                          background: k >= 2 ? "var(--clay-line)" : "var(--sage-line)",
                        }} />
                        <div className="tiny faint" style={{ marginTop: 3 }}>KL{k}</div>
                      </div>
                    );
                  })}
                </div>
                <div className="tiny dim" style={{ marginTop: 8, lineHeight: 1.5 }}>
                  Prevalence was tuned to sit near the ~28.7% pooled Indian community estimate
                  (Pal et al., 2016), not chosen for convenience.
                </div>
              </div>
            </div>
          </Card>

          <Card>
            <CardHead title="Model" sub="written from scratch — ml/gbm.py" icon={<IcModel size={14} />} />
            <div className="card-bd">
              <div className="kv"><dt>Family</dt><dd>Gradient-boosted trees</dd></div>
              <div className="kv"><dt>Trees</dt><dd>{metrics.model.trees} (early stopped)</dd></div>
              <div className="kv"><dt>Depth</dt><dd>{metrics.model.depth}</dd></div>
              <div className="kv"><dt>Learning rate</dt><dd>{metrics.model.lr}</dd></div>
              <div className="kv"><dt>Inputs</dt><dd>{metrics.model.n_features}</dd></div>
              <div className="kv"><dt>Bundle size</dt><dd>149 KB JSON</dd></div>
              <div className="tiny dim" style={{ marginTop: 12, lineHeight: 1.55 }}>
                No xgboost, no TFLite, no ONNX. The booster is ours, so the export is a plain JSON
                array of trees that a 60-line TypeScript function evaluates on the phone — with no
                toolchain in the loop and no chance of version skew between training and inference.
                <span style={{ color: "var(--sage-ink)", fontWeight: 550 }}> Parity is enforced by a test:
                worst observed drift 1.7 × 10⁻¹².</span>
              </div>
            </div>
          </Card>

          <Card style={{ background: "var(--surface-2)" }}>
            <CardHead title="Known limitations" sub="the list a reviewer would write for us" icon={<IcAlert size={14} />} />
            <div className="card-bd">
              <ol style={{ margin: 0, paddingLeft: 17, fontSize: 12.6, lineHeight: 1.65, color: "var(--ink-2)" }}>
                <li><strong>No patient has been screened.</strong> Everything is simulator-derived. Discrimination on real captures will be lower — noisier signals, worse strap placement, non-compliant walking.</li>
                <li><strong>The label is a proxy.</strong> KL ≥ 2 is radiographic, and the plan is to validate against a PHC radiograph read by a clinician, not against the simulator.</li>
                <li><strong>Symptoms are self-reported.</strong> WOMAC carries real importance here, and it can be gamed or misunderstood in translation.</li>
                <li><strong>Unilateral disease.</strong> One kit measures one knee. Bilateral asymmetry is currently an input, not an output.</li>
                <li><strong>Population drift.</strong> The occupation and terrain priors are NER-specific by design; the model should not be deployed elsewhere without refitting.</li>
                <li><strong>No fairness audit yet.</strong> Sex is an input and carries weight. Subgroup performance must be reported before any deployment.</li>
              </ol>
            </div>
          </Card>
        </div>

        {/* --------------------------------------------- feature stats --- */}
        <Section title="Feature separation" sub="Mean value in each class on the training cohort. A feature whose two means sit on top of each other is carrying nothing.">
          <Card>
            <div style={{ overflowX: "auto", maxHeight: 460 }}>
              <table className="tbl" style={{ fontSize: 12.4 }}>
                <thead>
                  <tr>
                    <th>Feature</th><th>Channel</th>
                    <th className="rt">KL &lt; 2 mean</th><th className="rt">KL ≥ 2 mean</th>
                    <th className="rt">Cohen&rsquo;s d</th><th style={{ width: 130 }}>Separation</th>
                  </tr>
                </thead>
                <tbody>
                  {[...metrics.feature_stats]
                    .map((f) => {
                      const pooled = Math.sqrt((f.neg_sd ** 2 + f.pos_sd ** 2) / 2) || 1e-9;
                      return { ...f, d: Math.abs(f.pos_mean - f.neg_mean) / pooled };
                    })
                    .sort((a, b) => b.d - a.d)
                    .map((f) => (
                      <tr key={f.feature}>
                        <td style={{ fontWeight: 530 }}>
                          {FEATURE_LABEL[f.feature]}{" "}
                          <span className="tiny faint">{FEATURE_UNIT[f.feature]}</span>
                        </td>
                        <td>
                          <span className={`chip ${CHANNEL_CHIP[FEATURE_CHANNEL[f.feature] ?? "intake"]}`} style={{ fontSize: 10.2 }}>
                            {CHANNEL_LABEL[FEATURE_CHANNEL[f.feature] ?? "intake"]}
                          </span>
                        </td>
                        <td className="rt num">{f.neg_mean.toFixed(2)}</td>
                        <td className="rt num">{f.pos_mean.toFixed(2)}</td>
                        <td className="rt num" style={{ fontWeight: 560 }}>{f.d.toFixed(2)}</td>
                        <td><Bar value={Math.min(1, f.d / 1.6)}
                                 tone={f.d > 0.8 ? "var(--sage-line)" : f.d > 0.35 ? "var(--amber-line)" : "var(--surface-3)"} /></td>
                      </tr>
                    ))}
                </tbody>
              </table>
            </div>
            <div className="card-ft">
              Cohen&rsquo;s d over the pooled standard deviation. Anything under about 0.2 is noise the
              booster is free to ignore — and mostly does, which is why the importance chart is short.
            </div>
          </Card>
        </Section>
      </div>
    </>
  );
}

function CMHead({ children }: { children: React.ReactNode }) {
  return <div className="eyebrow" style={{ textAlign: "center", paddingBottom: 2 }}>{children}</div>;
}
function CMSide({ children }: { children: React.ReactNode }) {
  return (
    <div className="eyebrow" style={{
      display: "flex", alignItems: "center", justifyContent: "flex-end",
      textAlign: "right", lineHeight: 1.25,
    }}>{children}</div>
  );
}
function CMCell({ n, total, label, tone, line, ink }: {
  n: number; total: number; label: string; tone: string; line: string; ink: string;
}) {
  return (
    <div style={{ background: tone, border: `1px solid ${line}`, borderRadius: "var(--r-sm)", padding: "12px 10px", textAlign: "center" }}>
      <div className="serif num" style={{ fontSize: 24, color: ink, lineHeight: 1 }}>{n}</div>
      <div className="num tiny" style={{ color: ink, opacity: .72, marginTop: 3 }}>{((n / total) * 100).toFixed(1)}%</div>
      <div className="tiny" style={{ color: ink, opacity: .62, marginTop: 4 }}>{label}</div>
    </div>
  );
}
function ConsequenceCard({ tone, line, ink, head, label, body }: {
  tone: string; line: string; ink: string; head: string; label: string; body: string;
}) {
  return (
    <div style={{ background: tone, border: `1px solid ${line}`, borderRadius: "var(--r)", padding: "13px 15px" }}>
      <div className="eyebrow" style={{ color: ink, opacity: .78 }}>{label}</div>
      <div className="serif num" style={{ fontSize: 23, color: ink, marginTop: 5, lineHeight: 1 }}>{head}</div>
      <div style={{ fontSize: 11.8, lineHeight: 1.55, color: ink, opacity: .82, marginTop: 8 }}>{body}</div>
    </div>
  );
}
